# Generated by Django 4.0.4 on 2022-05-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_post',
            field=models.ManyToManyField(to='newsportal.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
