# Generated by Django 4.0.2 on 2022-05-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0005_alter_post_category_post_delete_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='имя категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='имя категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_post_en',
            field=models.TextField(help_text='тело новости', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_post_ru',
            field=models.TextField(help_text='тело новости', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_post_en',
            field=models.TextField(help_text='название новости', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_post_ru',
            field=models.TextField(help_text='название новости', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='имя категории', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_post',
            field=models.ForeignKey(help_text='автор новости', on_delete=django.db.models.deletion.CASCADE, to='newsportal.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_post',
            field=models.TextField(help_text='тело новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_post',
            field=models.ManyToManyField(to='newsportal.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.TextField(help_text='название новости'),
        ),
    ]
